### ISSUE TITLE
Support accents in searches

### ISSUE THREAD

**Issue by mgibbs189** [mgibbs189/fSelect#16]
If I search on "Domaine d'activité" "meca" or "méca" I do not have the same results.

Help Scout #8024

**Comment by Rahe** [comment]
Hello,
Have you any news about this issue ? :)

**Comment by Rahe** [comment]
Hello,
Any news maybe ^^ ?

**Comment by firestar300** [comment]
Same problem here.

**Comment by MaximeCulea** [comment]
@mgibbs189, are you still alive ?

**Comment by mgibbs189** [comment]
Thanks again for the PR @firestar300

**Comment by firestar300** [comment]
You are welcome.

**Comment by MaximeCulea** [comment]
Awesome! Thank you @firestar300 @mgibbs189 🤗

**Comment by MaximeCulea** [comment]
Awesome! Thank you @firestar300 @mgibbs189 🤗 
Does it means it is already available into a new Facet WP release ?

**Comment by mgibbs189** [comment]
It will be included in the next version (3.2.8), which will be released this week.

**Comment by MaximeCulea** [comment]
Perfecto! :)
