### ISSUE TITLE
How to dynamically select items ?

### ISSUE THREAD

**Issue by Fredpeyr** [mgibbs189/fSelect#19]
Hi and congratulations for fselect ! It's very great !

I'm using it in multiselect mode, and i easyly obtain the items selected in a string table. Good ! So i can convert my string table to a string like this : "option2|option6|option8" and store it into my database.

But i want now do the inverse.
So i read my record, and i split my field "option2|option6|option8" into a string table of 3 items.
And i want items to be selected automatically with this string table and i can't find samples to do it.

I see in your sample :  "< option value="2" selected>Option 2</option >"
It works well of course, but how can i have the same result programmatically ?

Thank's by advance.
Fred.

**Comment by marcosoliveiradev** [comment]
Select items dinamically. Anyone has a solution for this???

**Comment by moh85** [comment]
hello all,
maybe this answer is late but I found a way and it's by clicking the option by this selector:
`$(".fs-option[data-value='29']").click();`

The value e.g. (29) is the value you want to select dynamically.

you can also multi-select more than one value using this code:

```
var values = '1,2,3,4,5';
$.each(values.split(","), function(i,val){
$(".fs-option[data-value='"+val+"']").click();
});
```

of course you can modify the code if you are using JS Array / JSON object by changing this part:
`values.split(",")` to `JsonValues `for example.

if you have more than select in one page, you may need to point a parent id / class in the selector for example:

`$("#parentDivId .fs-option[data-value='"+val+"']").click();`

**Comment by marcosoliveiradev** [comment]
Perfect!!!  Simple and great solution!!!
Thanks, @moh85 !!!
