### ISSUE TITLE
Any way to dynamically change the values?

### ISSUE THREAD

**Issue by ralphmorris** [mgibbs189/fSelect#21]
Looks nice. Any way to dynamically change the values when changing the underlying select value?

eg.
```
$('select').val('someoption');
```

**Comment by Dunnbar** [comment]
Any changes about this ?

**Comment by moh85** [comment]
hello all,
maybe this answer is late but I found a way and it's by clicking the option by this selector:
`$(".fs-option[data-value='29']").click();`

The value e.g. (29) is the value you want to select dynamically.

you can also multi-select more than one value using this code:

```
var values = '1,2,3,4,5';
$.each(values.split(","), function(i,val){
$(".fs-option[data-value='"+val+"']").click();
});
```

of course you can modify the code if you are using JS Array / JSON object by changing this part:
`values.split(",")` to `JsonValues `for example.

if you have more than select in one page, you may need to point a parent id / class in the selector for example:

`$("#parentDivId .fs-option[data-value='"+val+"']").click();`

**Comment by moh85** [comment]
hello all,
maybe this answer is late but I found a way and it's by clicking the option by this selector:
`$(".fs-option[data-value='29']").click();`

The value e.g. (29) is the value you want to select dynamically.

you can also multi-select more than one value using this code:

```
var values = '1,2,3,4,5';
$.each(values.split(","), function(i,val){
$(".fs-option[data-value='"+val+"']").click();
});
```

of course you can modify the code if you are using JS Array / JSON object by changing this part:
`values.split(",")` to `JsonValues `for example.

if you have more than select in one page, you may need to point a parent id / class in the selector for example:

`$("#parentDivId .fs-option[data-value='"+val+"']").click();`
