### ISSUE TITLE
Any way to add 'required' class on.change invalid?

### ISSUE THREAD

**Issue by graphcom1** [mgibbs189/fSelect#22]
I've been experimenting with trying to add a class to .fs-wrap parent div if select is invalid.  This function works to add the class to the hidden select element:

$('#formID select').on('change invalid', function() {
    var selectfield = $(this).get(0);
    if (!selectfield.validity.valid) {
	  selectfield.classList.add('redborder');
    }
});

But I can't figure out how to add a class to parent div though.  Would you have any ideas?

**Comment by mgibbs189** [comment]
@graphcom1 what makes a select `invalid`?
