### ISSUE TITLE
How to add Select All Option 

### ISSUE THREAD

**Issue by Gautam2010** [mgibbs189/fSelect#26]
Add select all check box to select all and deselect all

**Comment by behzadba** [comment]
I came here to ask the exact same request!! 
This is a great module. Can someone just add Select All option please?

**Comment by macmessa** [comment]
Nice job @behzadba, I've just added the **selectAllText** in my version.

**Comment by karoljoc** [comment]
Great work !! Have been looking for a select like this for a while now :-) Would you be nice if the select all did not look like the existing options. For example:
![image](https://user-images.githubusercontent.com/3934410/46258854-01128500-c4d1-11e8-9fa8-00c9be556c0e.png)

Would also be great if the "Select All" text was a parameter so it can be internationalized.

**Comment by mgibbs189** [comment]
You can also select the first option, then `SHIFT + click` the last option to select all options in between.

**Comment by shahidt** [comment]
Why is this issue closed? Shouldn't behzadba do a pull request and incorporate the 'Select All' feature into this main plugin? Better to not fork for a single feature.
