### ISSUE TITLE
Destroy fselect when appending dynamic content

### ISSUE THREAD

**Issue by mukkaramwaheed** [mgibbs189/fSelect#34]
When i append new content in dropdown using **AJAX**  than i  want to destroy to instance first than initialize again. How can i do this? I didn't found any destroy method in this library.

**Comment by fabiofvieira** [comment]
You can use **$('.fselect').fSelect('reload')** to this, but they duplicate search field

**Comment by mukkaramwaheed** [comment]
This could not work as expected. It will duplicate the search field infinite time again and again. Any other possible solution?

**Comment by fabiofvieira** [comment]
I did this to get around the problem and it worked for me.
`jQuery(combo).siblings('.fs-dropdown').find('.fs-search,.fs-no-results').remove();
 jQuery(combo).fSelect('reload');`

**Comment by fabiofvieira** [comment]
Yes it's a bug, the reload method not check if already exists this elements before append it

**Comment by mgibbs189** [comment]
@fabiofvieira in the meantime you could call `destroy` then `create`, it'd be a bit cleaner.

```js
$el.fSelect('destroy');
$el.fSelect('create');
```

**Comment by mgibbs189** [comment]
Better yet, fSelect('reload') should work better now 👍 

/cc @fabiofvieira @mukkaramwaheed
