### ISSUE TITLE
Placeholder for single selection dropdowns?

### ISSUE THREAD

**Issue by d33pak-s1ngh** [mgibbs189/fSelect#35]
The Placeholder for single selection dropdown is not working, In Single selection dropdown it selects first item by default. I want to show placeholder in single selection dropdown also.
Please let me know if there is such option.

**Comment by stranoweb** [comment]
Same here, I'd like to have that option too

**Comment by L3Home** [comment]
The way HTML works, the first option is always selected (if another option is not). This is the standard behavior, unfortunately. The only way to show a "placeholder" for a single-selection dropdown is to add an option to the beginning of your list that has your placeholder text (and either no value, or a value of your choosing).

If you want to force the user to select an option before posting, add a check for the value, and if it's either blank, or is the value of your placeholder option, return false (and perhaps notify the user of the issue).

**Comment by mgibbs189** [comment]
^ this.
