### ISSUE TITLE
fselect reload is not working.

### ISSUE THREAD

**Issue by d33pak-s1ngh** [mgibbs189/fSelect#36]
On click event of a button I want to reset a dropdown which means I want to uncheck all selected options.
`$("select#stage").fselect("reload")` is not doing anything.

**Comment by mgibbs189** [comment]
`reload` does not change any choices, it simply re-applies the UI on top of the `<select>`.

You'd need to empty the dropdown's values manually `$('select').empty()` then trigger `reload` so that fSelect knows about the changes.

**Comment by uzair-hameedd** [comment]
I use fSelect for select with checkboxes and search filter. All features seems good. But When I use jquery function  .prop() or .attr() for disabled multi select dropdown its not disabled.
