### ISSUE TITLE
Why the 'fs-label-selected' class has been removed from reloadDropdownLabel: function() ?

### ISSUE THREAD

**Issue by stranoweb** [mgibbs189/fSelect#37]
I've downloaded the updated version of fSelect.js and the part that adds the class fs-label-selected has been completelly removed, it was usefull to me, apart the fact that it was always added on single select.
On multiple select it was working fine though.

**Comment by mgibbs189** [comment]
@stranoweb I don't recall fSelect ever having that CSS class. Could you point me to a commit where `.fs-label-selected` exists?

**Comment by stranoweb** [comment]
I may have actually added myself because I needed, just forgot I did it!
It's usefull if you want to highlight the selected option, in my case I'm using your plugin on a search form and the selected fields have a different background color.
This is the code I've added to your plugin, in case you want to add to it on the next release:

`reloadDropdownLabel: function() {
                var settings = this.settings;
                var labelText = [];
                var labelwrap = this.$wrap.find('.fs-label-wrap');

                this.$select.each(function(){
                  if($(this).val()!=''){
                        labelwrap.addClass('fs-label-selected');
                    }else{
                        labelwrap.removeClass('fs-label-selected');
                      }
                    });

                this.$wrap.find('.fs-option.selected').each(function(i, el) {
                    labelText.push($(el).find('.fs-option-label').html());
                });

                if (labelText.length < 1) {
                    labelText = settings.placeholder;
                    labelwrap.removeClass('fs-label-selected');
                }
                else if (labelText.length > settings.numDisplayed) {
                    labelText = settings.overflowText.replace('{n}', labelText.length);
                }
                else {
                    labelText = labelText.join(', ');
                }

                this.$wrap.find('.fs-label').html(labelText);
                this.$wrap.toggleClass('fs-default', labelText === settings.placeholder);
                if (this.$wrap.find('.fs-dropdown').hasClass('hidden') === false) {
                this.$select.change();
                }
            }`
