### ISSUE TITLE
Regarding X button at search input.

### ISSUE THREAD

**Issue by mikip91** [mgibbs189/fSelect#40]
Hi Team,

I am able to use fselect correctly but can't seen to populate the cross button beside search which is really needed for my website. Could you please help?

**Comment by L3Home** [comment]
I've submitted a fork/change request that fixes the X that appears in HTML5-compliant browsers.

**Comment by mikip91** [comment]
Thanks @L3Home

**Comment by mgibbs189** [comment]
Closing, we just switched the input type to `text` in e1ee306 to prevent these cross-browser compatibility issues (e.g. the "x" button which varies depending on the browser).
