### ISSUE TITLE
multi selected item to be load with option

### ISSUE THREAD

**Issue by setlec** [mgibbs189/fSelect#47]
Hello there, i need to load a table with many selected items and give those selected items a disabled option.

exemple:   say that someone selected C++ and JSP previously for his profile and another person that is recommending someone the use of C . the code on the html page should be like this. 

```
<select class="demo" multiple="multiple">
  <optgroup label="Languages">
      <option value="cp" selected disabled>C++</option>
      <option value="cs">C#</option>
      <option value="oc">Object C</option>
      <option value="c" selected>C</option>
  </optgroup>
  <optgroup label="Scripts">
      <option value="js">JavaScript</option>
      <option value="php">PHP</option>
      <option value="asp">ASP</option>
      <option value="jsp" selected disabled>JSP</option>
  </optgroup>
</select>
```
ofc i make an array to check what item was previously selected and disable them. my issue is that when i do disable those items  they do not get the selected option and end up being just disabled and not selected.

**Comment by mgibbs189** [comment]
If you use `.val()` on that example `<select>` with fSelect disabled, does JSP and C++ get returned? E.g. do normal HTML selects return the value of disabled choice?

**Comment by setlec** [comment]
Hello, due to late reply, I've did a control through laravel:
<select class="demo" multiple="multiple">
  <optgroup label="Languages">
      <option value="cp" selected disabled>C++</option>
      <option value="cs">C#</option>
      <option value="oc">Object C</option>
      <option value="c" selected>C</option>
  </optgroup>
@foreach ($script as $item)
<optgroup label="Scripts">
   <option value="{{ $item->id }}" @if ($item->id == $script->id)selected disabled@endif>{{ $item->name}}</option>
@endforeach
 </optgroup>
</select>
