### ISSUE TITLE
Problem with "true" / "false" values of select

### ISSUE THREAD

**Issue by mranisz** [mgibbs189/fSelect#52]
Hi,
if select has the values "true" / "false", there is a problem with setting the correct value while fSelect is changed (the "true" / "false" values are converted to boolean and should remain strings). I suggest the following changes (v. 1.0):
line 224: selected.push($(el).attr('data-value')); ---> selected.push('' + $(el).attr('data-value'));
line 228: var selected = $(this).attr('data-value'); ---> var selected = '' + $(this).attr('data-value');

**Comment by mgibbs189** [comment]
@mranisz Which browser are you seeing this issue with? I created a quick test setup (Firefox) and the values seem to be correctly preserved as strings.

```js
jQuery('body').prepend('<select class="myselect" multiple="multiple"><option value="true">true</option><option value="false">false</option></select>');
jQuery('.myselect').fSelect();
// after selecting some choices, run the following...
jQuery('.myselect').val()
```

**Comment by mranisz** [comment]
Sorry, the problem is only with the select, which is not multiple.

**Comment by mgibbs189** [comment]
No difference, still showing a string for me. Again, which browser?

**Comment by mranisz** [comment]
Google Chrome v. 78.0.3904.108 (64 bit) (Ubuntu 18.04.3)
jQuery v3.2.1
(after changing the value by fSelect ('.myselect').val() returns null)

**Comment by mgibbs189** [comment]
See https://d.pr/v/N37Pid

jQuery 3.4.1, latest fSelect, Chrome 78. Still not able to duplicate the issue...

**Comment by mranisz** [comment]
Sorry, it was my fault.
I have accidentally changed in your code: .attr('data-...'), to .data('...') and after it "true" was returned as true (boolean). In the original code everything works fine. Thank you.
