### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by sc0ttkclark** [mgibbs189/fSelect#7]
Just adding this so it doesn't get left behind, fSelect needs to ensure it's accessible in any way it can, I'm not as familiar with the specific things it needs to do but I know that Select2 has issues that have been talked about here:

https://make.wordpress.org/accessibility/2015/09/07/accessibility-usertest-select2/

**Comment by mgibbs189** [comment]
fSelect is now fully keyboard-friendly, which is a nice step forward. I'll continue experimenting with making it fully JAWS-compatible.
